"""Target catalogs for the proximity-ordered RV survey.

Two catalogs:
- TARGET_CATALOG: the curated Phase 7 list (10 stars, hand-checked
  parameters). Curated entries always win lookups.
- Shell catalog (Phase 8.4): generated by SIMBAD TAP query, all FGK
  dwarfs within a distance limit, grouped into distance shells.
  Cached in data/shell_catalog.json. SIMBAD is used instead of Gaia
  DR3 because the brightest nearest stars (e.g. Alpha Cen A) are
  missing or unreliable in Gaia.

Also provides identifier resolution (Gaia DR3, TIC via SIMBAD) and
TESS availability checks.
"""

import json
import logging
import os
import re
from datetime import datetime

logger = logging.getLogger(__name__)

SHELL_CATALOG_PATH = os.path.join("data", "shell_catalog.json")

# Distance shells (pc), survey runs nearest shell first
SHELLS = ((0.0, 6.0), (6.0, 10.0), (10.0, 15.0))

# Phase 7 target catalog -- 10 prioritized stars from phase7_exo_earth_poc.md
# Section 3.5. Ordered by priority (proximity + solar similarity + data richness).
#
# Identifiers will be populated/validated at runtime via SIMBAD resolution
# for any missing Gaia DR3 source_id or TIC values.
TARGET_CATALOG = [
    {
        "name": "Alpha Centauri A",
        "hd": "HD 128620",
        "hip": 71683,
        "tic": None,  # resolved at runtime; TESS saturated for this target
        "gaia_dr3_id": None,  # resolved at runtime via SIMBAD
        "spectral_type": "G2V",
        "teff_k": 5790,
        "distance_pc": 1.34,
        "mass_msun": 1.10,
        "feh": 0.20,
        "tier": "A/B",
        "known_planets": 1,
        "planet_status": "1 unconfirmed candidate",
        "notes": "Nearest G2V; binary with alpha Cen B; TESS saturated",
    },
    {
        "name": "Tau Ceti",
        "hd": "HD 10700",
        "hip": 8102,
        "tic": None,
        "gaia_dr3_id": None,
        "spectral_type": "G8.5V",
        "teff_k": 5375,
        "distance_pc": 3.65,
        "mass_msun": 0.78,
        "feh": -0.50,
        "tier": "C",
        "known_planets": 4,
        "planet_status": "4 unconfirmed candidates (e,f,g,h)",
        "notes": "9000+ HARPS measurements; low metallicity; debris disk",
    },
    {
        "name": "82 G. Eridani",
        "hd": "HD 20794",
        "hip": 15510,
        "tic": None,
        "gaia_dr3_id": None,
        "spectral_type": "G6V",
        "teff_k": 5401,
        "distance_pc": 6.04,
        "mass_msun": 0.70,
        "feh": -0.40,
        "tier": "C",
        "known_planets": 3,
        "planet_status": "3 confirmed (d in HZ, 5.8 Mearth)",
        "notes": "Primary validation target; HARPS + ESPRESSO data",
    },
    {
        "name": "Eta Cassiopeiae A",
        "hd": "HD 4614",
        "hip": 3821,
        "tic": None,
        "gaia_dr3_id": None,
        "spectral_type": "G0V",
        "teff_k": 6012,
        "distance_pc": 5.92,
        "mass_msun": 1.03,
        "feh": -0.30,
        "tier": "B",
        "known_planets": 1,
        "planet_status": "1 unconfirmed (~22 Mearth)",
        "notes": "Wide binary (70+ AU separation)",
    },
    {
        "name": "Delta Pavonis",
        "hd": "HD 190248",
        "hip": 99240,
        "tic": None,
        "gaia_dr3_id": None,
        "spectral_type": "G8IV-V",
        "teff_k": 5604,
        "distance_pc": 6.11,
        "mass_msun": 1.05,
        "feh": 0.33,
        "tier": "B/C",
        "known_planets": 0,
        "planet_status": "None (deep RV limits K < 1 m/s)",
        "notes": "CORALIE + HARPS since 1998; subgiant boundary",
    },
    {
        "name": "61 Virginis",
        "hd": "HD 115617",
        "hip": 64924,
        "tic": None,
        "gaia_dr3_id": None,
        "spectral_type": "G7V",
        "teff_k": 5531,
        "distance_pc": 8.53,
        "mass_msun": 0.94,
        "feh": -0.02,
        "tier": "C",
        "known_planets": 3,
        "planet_status": "3 confirmed (b, c, d)",
        "notes": "Near-solar metallicity; multi-planet system",
    },
    {
        "name": "Beta CVn",
        "hd": "HD 109358",
        "hip": 61317,
        "tic": None,
        "gaia_dr3_id": None,
        "spectral_type": "G0V",
        "teff_k": 5880,
        "distance_pc": 8.44,
        "mass_msun": 1.02,
        "feh": -0.21,
        "tier": "B",
        "known_planets": 0,
        "planet_status": "None",
        "notes": "Also known as Chara; quiet single star",
    },
    {
        "name": "Zeta Tucanae",
        "hd": "HD 1581",
        "hip": 1599,
        "tic": None,
        "gaia_dr3_id": None,
        "spectral_type": "F9.5V",
        "teff_k": 5956,
        "distance_pc": 8.60,
        "mass_msun": 0.99,
        "feh": -0.15,
        "tier": "B",
        "known_planets": 0,
        "planet_status": "None",
        "notes": "At upper Teff boundary; slow rotator confirmed",
    },
    {
        "name": "18 Scorpii",
        "hd": "HD 146233",
        "hip": 79672,
        "tic": None,
        "gaia_dr3_id": None,
        "spectral_type": "G2Va",
        "teff_k": 5817,
        "distance_pc": 14.13,
        "mass_msun": 1.02,
        "feh": 0.05,
        "tier": "A",
        "known_planets": 1,
        "planet_status": "1 candidate (super-Earth, P~19.9d)",
        "notes": "Nearest solar twin; beyond 10 pc but high value",
    },
    {
        "name": "HD 134060",
        "hd": "HD 134060",
        "hip": 74273,
        "tic": None,
        "gaia_dr3_id": None,
        "spectral_type": "G0V",
        "teff_k": 5890,
        "distance_pc": 24.15,
        "mass_msun": 1.07,
        "feh": 0.10,
        "tier": "B",
        "known_planets": 2,
        "planet_status": "2 confirmed (b: 3.3d, c: 1168d)",
        "notes": "Beyond 10 pc; long-period planet c in wide orbit",
    },
]


def get_targets():
    """Return the full Phase 7 target catalog.

    Returns
    -------
    list[dict]
        List of target dictionaries.
    """
    return list(TARGET_CATALOG)


def _norm_id(s):
    """Normalize an identifier for matching ('HD  10700' -> 'hd 10700')."""
    return re.sub(r"\s+", " ", str(s).strip().lower())


def _match_target(target, name_norm):
    if _norm_id(target["name"]) == name_norm:
        return True
    if target.get("hd") and _norm_id(target["hd"]) == name_norm:
        return True
    if target.get("hip") and f"hip {target['hip']}" == name_norm:
        return True
    return False


def get_target(name):
    """Look up a target by common name, HD number, or HIP number.

    Searches the curated Phase 7 catalog first (hand-checked
    parameters win), then the generated shell catalog (Phase 8.4).

    Parameters
    ----------
    name : str
        Target identifier (case-insensitive). Matches against 'name',
        'hd', or 'HIP <number>'.

    Returns
    -------
    dict or None
        Target dictionary, or None if not found.
    """
    name_norm = _norm_id(name)
    for target in TARGET_CATALOG:
        if _match_target(target, name_norm):
            return dict(target)
    for target in load_shell_catalog():
        if _match_target(target, name_norm):
            return dict(target)
    logger.warning("Target '%s' not found in catalog", name)
    return None


def resolve_target_ids(target):
    """Resolve missing identifiers (Gaia DR3, TIC) via SIMBAD.

    Queries SIMBAD for the target and extracts Gaia DR3 source_id and
    TIC ID from the identifier list.

    Parameters
    ----------
    target : dict
        Target dictionary from the catalog.

    Returns
    -------
    dict
        Updated target dictionary with resolved IDs. Unresolved IDs remain None.
    """
    from astroquery.simbad import Simbad
    import re

    result = dict(target)
    name = target["name"]
    logger.info("Resolving identifiers for %s", name)

    # Try common name first, then HD number as fallback
    search_names = [name]
    if target.get("hd") and target["hd"] != name:
        search_names.append(target["hd"])

    id_table = None
    for search_name in search_names:
        try:
            id_table = Simbad.query_objectids(search_name)
            if id_table is not None and len(id_table) > 0:
                logger.info("SIMBAD resolved '%s' via query name '%s'", name, search_name)
                break
        except Exception as e:
            logger.warning("SIMBAD query_objectids failed for '%s': %s", search_name, e)

    if id_table is None or len(id_table) == 0:
        logger.warning("No SIMBAD identifiers found for '%s'", name)
        return result

    for row in id_table:
        id_str = str(row["id"]).strip()

        # Gaia DR3
        if result["gaia_dr3_id"] is None:
            match = re.match(r"Gaia DR3\s+(\d+)", id_str)
            if match:
                result["gaia_dr3_id"] = match.group(1)
                logger.info("  Gaia DR3: %s", result["gaia_dr3_id"])

        # TIC
        if result["tic"] is None:
            match = re.match(r"TIC\s+(\d+)", id_str)
            if match:
                result["tic"] = int(match.group(1))
                logger.info("  TIC: %d", result["tic"])

    if result["gaia_dr3_id"] is None:
        logger.warning("Could not resolve Gaia DR3 ID for '%s'", name)
    if result["tic"] is None:
        logger.info("No TIC ID found for '%s' (may be too bright for TESS)", name)

    return result


def validate_against_gaia(target):
    """Validate catalog values against Gaia DR3.

    Queries Gaia DR3 for the target and compares Teff and distance
    against the catalog values.

    Parameters
    ----------
    target : dict
        Target dictionary (must have 'gaia_dr3_id' resolved, or 'name' for
        SIMBAD fallback).

    Returns
    -------
    dict
        Validation report with keys: gaia_data (raw Gaia result),
        teff_match (bool), teff_catalog, teff_gaia, teff_diff_pct,
        distance_match (bool), distance_catalog, distance_gaia, distance_diff_pct.
        Returns None if Gaia query fails.
    """
    from src.data_access import query_stars_by_id, resolve_simbad_name

    gaia_id = target.get("gaia_dr3_id")
    if gaia_id is None:
        # Try resolving via SIMBAD
        gaia_id = resolve_simbad_name(target["name"])
        if gaia_id is None:
            logger.warning("Cannot validate %s: no Gaia DR3 ID", target["name"])
            return None

    logger.info("Validating %s against Gaia DR3 (source_id=%s)", target["name"], gaia_id)
    stars = query_stars_by_id([gaia_id])

    if not stars:
        logger.warning("Gaia DR3 returned no data for source_id=%s", gaia_id)
        return None

    gaia = stars[0]
    report = {"gaia_data": gaia}

    # Teff comparison
    teff_gaia = gaia.get("teff_gspphot")
    teff_catalog = target.get("teff_k")
    if teff_gaia is not None and teff_catalog is not None:
        diff_pct = abs(teff_gaia - teff_catalog) / teff_catalog * 100
        report["teff_catalog"] = teff_catalog
        report["teff_gaia"] = teff_gaia
        report["teff_diff_pct"] = round(diff_pct, 1)
        report["teff_match"] = diff_pct < 5.0  # within 5%
    else:
        report["teff_match"] = None

    # Distance comparison
    dist_gaia = gaia.get("ref_distance_pc")
    dist_catalog = target.get("distance_pc")
    if dist_gaia is not None and dist_catalog is not None:
        diff_pct = abs(dist_gaia - dist_catalog) / dist_catalog * 100
        report["distance_catalog"] = dist_catalog
        report["distance_gaia"] = dist_gaia
        report["distance_diff_pct"] = round(diff_pct, 1)
        report["distance_match"] = diff_pct < 10.0  # within 10%
    else:
        report["distance_match"] = None

    logger.info("Validation for %s: Teff match=%s, distance match=%s",
                target["name"], report.get("teff_match"), report.get("distance_match"))
    return report


def check_tess_availability(target):
    """Check TESS light curve availability for a target.

    Parameters
    ----------
    target : dict
        Target dictionary.

    Returns
    -------
    dict
        Availability report with keys: available (bool), n_sectors (int),
        mission, author. Returns None if query fails.
    """
    from src.lightcurve import search_lightcurve

    # Try TIC ID first, then HD name, then common name
    search_names = []
    if target.get("tic"):
        search_names.append(f"TIC {target['tic']}")
    search_names.append(target["hd"])
    search_names.append(target["name"])

    for search_name in search_names:
        logger.info("Checking TESS availability for %s (searching as '%s')",
                     target["name"], search_name)
        try:
            info = search_lightcurve(search_name, mission="TESS")
            if info is not None:
                return {
                    "available": True,
                    "n_sectors": info["n_available"],
                    "mission": info["mission"],
                    "author": info["author"],
                    "search_name": search_name,
                }
        except Exception as e:
            logger.warning("TESS search failed for '%s': %s", search_name, e)

    logger.info("No TESS data found for %s", target["name"])
    return {"available": False, "n_sectors": 0, "mission": None, "author": None}


def resolve_all_targets():
    """Resolve identifiers for all targets in the catalog.

    Returns
    -------
    list[dict]
        List of target dictionaries with resolved Gaia DR3 and TIC IDs.
    """
    resolved = []
    for target in TARGET_CATALOG:
        resolved_target = resolve_target_ids(target)
        resolved.append(resolved_target)
    return resolved


# ============================================================
# Shell catalog generation (Phase 8.4)
# ============================================================

# Dwarf spectral type -> (Teff K, mass Msun) anchors, Pecaut & Mamajek
# (2013) main-sequence table. Interpolated linearly on subclass.
# Approximate by design: generated targets carry teff_source =
# "sptype_approx"; Gaia validation refines them per target later.
_SPTYPE_ANCHORS = {
    "F0": (7220, 1.59), "F2": (6820, 1.38), "F5": (6550, 1.33),
    "F8": (6170, 1.18), "G0": (5930, 1.06), "G2": (5790, 1.02),
    "G5": (5660, 0.93), "G8": (5490, 0.87), "K0": (5280, 0.81),
    "K2": (5040, 0.74), "K3": (4830, 0.73), "K4": (4620, 0.71),
    "K5": (4410, 0.68), "K7": (4070, 0.63), "K9": (3940, 0.60),
}


def _sptype_index(letter, subclass):
    """Map (letter, subclass) to a single numeric scale for interpolation."""
    base = {"F": 0.0, "G": 10.0, "K": 20.0}[letter]
    return base + float(subclass)


def _interp_anchor(letter, subclass, which):
    """Interpolate Teff (which=0) or mass (which=1) from the anchors."""
    x = _sptype_index(letter, subclass)
    pts = sorted(
        (_sptype_index(k[0], float(k[1:])), v[which])
        for k, v in _SPTYPE_ANCHORS.items()
    )
    xs = [p[0] for p in pts]
    ys = [p[1] for p in pts]
    if x <= xs[0]:
        return ys[0]
    if x >= xs[-1]:
        return ys[-1]
    for i in range(1, len(xs)):
        if x <= xs[i]:
            frac = (x - xs[i - 1]) / (xs[i] - xs[i - 1])
            return ys[i - 1] + frac * (ys[i] - ys[i - 1])
    return ys[-1]


def parse_spectral_type(sp_type):
    """Parse a SIMBAD spectral type string for an FGK dwarf.

    Handles component suffixes ("F5IV-V+DQZ" -> primary only),
    emission/metallicity notes ("K6VeFe-1"), and half subclasses
    ("G8.5V", "K2.5V").

    Parameters
    ----------
    sp_type : str
        SIMBAD sp_type string.

    Returns
    -------
    dict or None
        {letter, subclass, luminosity_class, teff_k, mass_msun} for
        an FGK dwarf (luminosity class V, IV-V, or absent), else None
        (giants, subgiants, non-FGK, unparseable).
    """
    if not sp_type:
        return None
    primary = str(sp_type).strip().split("+")[0].strip()

    m = re.match(r"^([FGK])\s*(\d(?:\.\d)?)?", primary)
    if not m:
        return None
    letter = m.group(1)
    subclass = float(m.group(2)) if m.group(2) else 5.0

    rest = primary[m.end():]
    # Longest-first so "IV-V" is not read as "IV" or "V"
    lum = None
    for cls in ("IV-V", "IV/V", "III", "II", "IV", "V", "I"):
        if cls in rest:
            lum = cls
            break
    if lum in ("III", "II", "I", "IV"):
        return None  # giants and pure subgiants are not survey targets
    if lum in ("IV/V",):
        lum = "IV-V"

    return {
        "letter": letter,
        "subclass": subclass,
        "luminosity_class": lum or "V (assumed)",
        "teff_k": round(_interp_anchor(letter, subclass, 0)),
        "mass_msun": round(_interp_anchor(letter, subclass, 1), 2),
    }


def _extract_identifier(ids_str, prefix):
    """Pull one identifier (e.g. 'HD 10700') from a SIMBAD ids string."""
    for token in str(ids_str).split("|"):
        token = re.sub(r"\s+", " ", token.strip())
        if token.startswith(prefix + " "):
            return token
    return None


def _clean_name(main_id):
    """Normalize a SIMBAD main_id ('*  61 Cyg A' -> '61 Cyg A')."""
    return re.sub(r"\s+", " ", str(main_id).lstrip("* ").strip())


def _hd_digits(hd):
    """'HD 165341A' -> '165341' (for component dedup grouping)."""
    m = re.search(r"(\d+)", hd or "")
    return m.group(1) if m else None


def assign_shell(distance_pc, shells=SHELLS):
    """Return the shell label ('0-6', '6-10', ...) for a distance."""
    for lo, hi in shells:
        if lo <= distance_pc < hi:
            return f"{lo:g}-{hi:g}"
    return None


def build_shell_catalog(max_distance_pc=15.0, teff_range=(4000, 6300),
                        save=True, path=SHELL_CATALOG_PATH):
    """Query SIMBAD TAP for all FGK dwarfs within a distance limit.

    Filters: parallax >= 1000/max_distance_pc, spectral type FGK with
    dwarf luminosity class, approximate Teff inside teff_range
    (default 4000-6300 K: ~F7V to K7V, K dwarfs included -- better RV
    targets than G at fixed distance). Requires an HD identifier
    (archives are keyed on HD). Composite rows (e.g. '70 Oph' when
    '70 Oph A' exists) are dropped in favor of the A component.

    Returns
    -------
    list[dict]
        Target dicts sorted by distance, cached to path when save=True.
    """
    from astroquery.simbad import Simbad

    plx_min = 1000.0 / max_distance_pc
    query = f"""
    SELECT b.main_id, b.plx_value AS plx, b.sp_type, b.otype, ids.ids
    FROM basic AS b JOIN ids ON b.oid = ids.oidref
    WHERE b.plx_value >= {plx_min:.4f}
      AND (b.sp_type LIKE 'F%' OR b.sp_type LIKE 'G%'
           OR b.sp_type LIKE 'K%')
    ORDER BY plx DESC
    """
    logger.info("SIMBAD TAP shell query: d < %.1f pc, Teff %s",
                max_distance_pc, teff_range)
    table = Simbad.query_tap(query)
    logger.info("SIMBAD returned %d raw rows", len(table))

    rows = []
    for row in table:
        rows.append({
            "main_id": str(row["main_id"]),
            "plx": float(row["plx"]),
            "sp_type": str(row["sp_type"]),
            "otype": str(row["otype"]),
            "ids": str(row["ids"]),
        })
    targets = filter_shell_rows(rows, teff_range=teff_range)

    if save:
        payload = {
            "generated_utc": datetime.utcnow().isoformat(),
            "query": {"max_distance_pc": max_distance_pc,
                      "teff_range": list(teff_range),
                      "source": "SIMBAD TAP"},
            "n_targets": len(targets),
            "targets": targets,
        }
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2)
        logger.info("Shell catalog saved: %s (%d targets)", path,
                    len(targets))
    return targets


def filter_shell_rows(rows, teff_range=(4000, 6300)):
    """Turn raw SIMBAD rows into shell-catalog target dicts.

    Separated from build_shell_catalog so it is testable offline.
    """
    candidates = []
    for row in rows:
        parsed = parse_spectral_type(row.get("sp_type"))
        if parsed is None:
            continue
        if not (teff_range[0] <= parsed["teff_k"] <= teff_range[1]):
            continue
        hd = _extract_identifier(row.get("ids"), "HD")
        if hd is None:
            continue  # archives (DACE/NASA) are keyed on HD
        plx = row.get("plx")
        if not plx or plx <= 0:
            continue
        distance = 1000.0 / plx
        hip = _extract_identifier(row.get("ids"), "HIP")
        hip_m = re.search(r"HIP (\d+)", hip) if hip else None
        candidates.append({
            "name": _clean_name(row["main_id"]),
            "hd": hd,
            "hip": int(hip_m.group(1)) if hip_m else None,
            "tic": None,
            "gaia_dr3_id": None,
            "spectral_type": re.sub(r"\s+", " ",
                                    str(row["sp_type"]).strip()),
            "teff_k": parsed["teff_k"],
            "distance_pc": round(distance, 2),
            "mass_msun": parsed["mass_msun"],
            "otype": row.get("otype"),
            "shell": assign_shell(distance),
            "source": "simbad_tap",
            "teff_source": "sptype_approx",
        })

    # Component dedup within one HD number: drop the composite row
    # only when a lettered 'A' component exists (70 Oph: HD 165341 +
    # HD 165341A + HD 165341B -> keep A and B). When only B exists
    # (eta Cas: HD 4614 + HD 4614B), the composite IS the primary.
    by_digits = {}
    for t in candidates:
        by_digits.setdefault(_hd_digits(t["hd"]), []).append(t)
    targets = []
    for group in by_digits.values():
        if len(group) == 1:
            targets.extend(group)
            continue
        has_a = any(re.search(r"\dA$", t["hd"]) for t in group)
        if has_a:
            targets.extend(t for t in group
                           if re.search(r"\d[A-Z]$", t["hd"]))
        else:
            targets.extend(group)

    targets.sort(key=lambda t: t["distance_pc"])
    logger.info("Shell catalog: %d targets after FGK-dwarf/Teff/HD "
                "filters and dedup", len(targets))
    return targets


def load_shell_catalog(path=SHELL_CATALOG_PATH):
    """Load the cached shell catalog. Returns [] if not generated."""
    if not os.path.exists(path):
        logger.warning("Shell catalog %s not found; run "
                       "build_shell_catalog() first", path)
        return []
    with open(path, "r", encoding="utf-8") as f:
        payload = json.load(f)
    return payload.get("targets", [])


def targets_in_shell(shell, catalog=None, include_curated=True):
    """Targets within a distance shell, nearest first.

    Merges curated TARGET_CATALOG entries in the shell with the
    generated catalog; curated entries win on HD-number collisions
    (hand-checked parameters, and it covers boundary disagreements
    like Delta Pavonis: G8IV in SIMBAD, G8IV-V in curated sources).

    Parameters
    ----------
    shell : tuple(float, float)
        (min_pc, max_pc), min inclusive, max exclusive.
    catalog : list[dict], optional
        Default: cached shell catalog.
    include_curated : bool
        Merge curated catalog entries within the shell (default True).
    """
    if catalog is None:
        catalog = load_shell_catalog()
    lo, hi = shell

    def in_shell(t):
        d = t.get("distance_pc")
        return d is not None and lo <= d < hi

    def key(t):
        # Full HD string, not digits: HD 165341A and HD 165341B are
        # different stars and must not collapse
        return _norm_id(t["hd"]) if t.get("hd") else t.get("name")

    picked = {}
    for t in catalog:
        if in_shell(t):
            picked[key(t)] = dict(t)
    if include_curated:
        for t in TARGET_CATALOG:
            if in_shell(t):
                picked[key(t)] = dict(t)  # curated wins

    result = list(picked.values())
    result.sort(key=lambda t: t["distance_pc"])
    return result
